### ISSUE TITLE
Syntay error

### ISSUE THREAD

**Issue by wolfgangr** [coddingtonbear/python-fs9721#3]
```
git clone https://github.com/coddingtonbear/python-fs9721.git
cd python-fs9721/
python2 install fs9721
python2 setup.py install
```

```
~/test/HP-90EPC/python-fs9721$ fs9721 /dev/ttyUSB0 
Traceback (most recent call last):
  File "/usr/local/bin/fs9721", line 11, in <module>
    load_entry_point('fs9721==1.2.1', 'console_scripts', 'fs9721')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/fs9721/__init__.py", line 2, in <module>
  File "build/bdist.linux-x86_64/egg/fs9721/client.py", line 4, in <module>
  File "build/bdist.linux-x86_64/egg/fs9721/value.py", line 2, in <module>
  File "/usr/local/lib/python2.7/dist-packages/measurement-4.0a5-py2.7.egg/measurement/base.py", line 11
    def qualname(obj: Any) -> str:
                    ^
SyntaxError: invalid syntax
```

```
python --version
Python 2.7.16
```

tried both `python` and `python2`, no difference

**Comment by wolfgangr** [comment]
will try my best with rudimentary python experience.
Looks like fs9721 was wirtten against measurement==1.7.2,
but there is a  4.0a5 now on github, which breaks the build.

So I'll try my best to build fs9721 with  measurement==1.7.3 
(1.7.2 is no longer on git)

what I did:
```
la /usr/local/lib/python2.7/dist-packages/
sudo rm -r /usr/local/lib/python2.7/dist-packages/measurement-4.0a5-py2.7.egg/

git clone --branch 1.7.3  https://github.com/coddingtonbear/python-measurement.git
cd python-measurement/


python setup.py build
sudo python setup.py install

...~/test/HoldPeak/python-measurement$ la /usr/local/lib/python2.7/dist-packages/
-rw-r--r-- 1 root staff   123 Jan 10 07:28 easy-install.pth
-rw-r--r-- 1 root staff 18445 Jan 10 06:43 fs9721-1.2.1-py2.7.egg
-rw-r--r-- 1 root staff 38802 Jan 10 07:27 measurement-1.7.3-py2.7.egg
drwxr-sr-x 3 root staff  4096 Jan 10 06:43 six-1.15.0-py2.7.egg
drwxr-sr-x 5 root staff  4096 Jan 10 07:28 sympy-0.7.6.1-py2.7.egg

cd ..
sudo rm -r python-fs9721/
sudo rm /usr/local/lib/python2.7/dist-packages/fs9721-1.2.1-py2.7.egg

git clone https://github.com/coddingtonbear/python-fs9721.git
cd python-fs9721/

python setup.py build
sudo python setup.py install
fs9721
```

**Comment by wolfgangr** [comment]
works
